//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Refit;
using WebApplication2;

namespace My.Client.Namespace
{
    public partial interface IWeatherForecastApi
    {
        [Get("/WeatherForecast")]
        Task<IEnumerable<WeatherForecast>> Get();
    }
}